trigger: none
pool: Ankitpool
stages:
- stage: terraforminit
  jobs:
  - job: initializejob
    steps:
    - task: TerraformInstaller@1
      displayName: tool install ho rha hai
      inputs:
        terraformVersion: 'latest'

    - task: tfsec@1
      displayName: security scan
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/parent'
    
    - task: TerraformTask@5
      displayName: plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
        environmentServiceNameAzureRM: 'ankitconn'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/parent'
        backendServiceArm: 'ankitconn'
        backendAzureRmStorageAccountName: 'ravsastg'
        backendAzureRmContainerName: 'stgcontainer'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      displayName: apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        environmentServiceNameAzureRM: 'ankitconn'